# Site settings
title: Iran University of Science and Technology
course_name: Advanced Programming (Spring 1397)
course_description: "This course introduces students with advanced programming with Java. Object-Oriented programming is the main subject of this course."
description: |
    Instructor: Mohammad Taher Pilehvar

message: Register to our <a href="https://quera.ir/course/2781/">Quera Class</a> to get course notifications via email.
baseurl: "/ap97" # the subpath of your site, e.g. /blog/
url: "http://miladibra10.github.io/" # the base hostname & protocol for your site
#syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-rmarkdown-syllabus-example.pdf"
githubdir: "miladibra10/github.miladibra10.io"

# Author/user information
email: pilehvar@iust.ac.ir
#twitter_username: 
github_username:  pilehvar
authorurl: "http://pilevar.com/taher/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

collections:
    events:
        output: true
    assignments:
        output: true
    lectures:
        output: ture
    announcements:

plugins:
    - jekyll-jalali
